import {BrowserRouter,useNavigate,useParams,Routes,Route,Link} from "react-router-dom";
import {useState} from "react";
import "./App.css";

const start=[{id:1,header:"React Assignment",description:"Complete React work",priority:"High",category:"Academic",raised:new Date().toLocaleString(),due:"28 Aug 2026",status:"Raised"}];

function Layout({children}){return <><nav><Link to="/">Dashboard</Link> <Link to="/tasks">Tasks</Link> <Link to="/add">Add Task</Link> <Link to="/completed">Completed</Link></nav>{children}</>}
function Dashboard({tasks}){return <div><h1>Task Dashboard</h1><p>Total Tasks: {tasks.length}</p><p>Closed Tasks: {tasks.filter(x=>x.status==="Closed").length}</p></div>}
function Tasks({tasks,setTasks,onlyClosed=false}){return <div><h1>{onlyClosed?"Completed Tasks":"Tasks"}</h1>{tasks.filter(t=>!onlyClosed||t.status==="Closed").map(t=><div className="card" key={t.id}><h3>{t.header}</h3><p>{t.description}</p><p>{t.priority} | {t.category} | {t.status}</p><Link to={`/tasks/${t.id}`}>Details</Link> <button onClick={()=>setTasks(tasks.filter(x=>x.id!==t.id))}>Delete</button></div>)}</div>}
function Add({tasks,setTasks}){const nav=useNavigate();const [f,setF]=useState({header:"",description:"",priority:"Medium",category:"Academic",due:"28 Aug 2026",status:"Raised"});function s(e){e.preventDefault();setTasks([...tasks,{...f,id:Date.now(),raised:new Date().toLocaleString()}]);nav("/tasks")}return <form onSubmit={s}><h1>Add Task</h1>{["header","description"].map(k=><input key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} required/>)}<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Academic</option><option>Personal</option></select><button>Add</button></form>}
function Details({tasks,setTasks}){const {id}=useParams();const t=tasks.find(x=>x.id===Number(id));if(!t)return <p>Task not found</p>;return <div><h1>{t.header}</h1><p>{t.description}</p><p>Priority: {t.priority}</p><p>Category: {t.category}</p><p>Raised: {t.raised}</p><p>Due: {t.due}</p><p>Status: {t.status}</p><button onClick={()=>setTasks(tasks.map(x=>x.id===t.id?{...x,status:x.status==="Closed"?"Pending":"Closed"}:x))}>Change Status</button></div>}
function App(){const [tasks,setTasks]=useState(start);return <BrowserRouter><Layout><Routes><Route path="/" element={<Dashboard tasks={tasks}/>}/><Route path="/tasks" element={<Tasks tasks={tasks} setTasks={setTasks}/>}/><Route path="/add" element={<Add tasks={tasks} setTasks={setTasks}/>}/><Route path="/tasks/:id" element={<Details tasks={tasks} setTasks={setTasks}/>}/><Route path="/completed" element={<Tasks tasks={tasks} setTasks={setTasks} onlyClosed/>}/></Routes></Layout></BrowserRouter>}
export default App;